# Generated by Django 5.1.7 on 2025-05-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voiture', models.CharField(max_length=100)),
                ('image_filename', models.TextField()),
                ('type', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('image_filename', models.TextField()),
                ('typeVoiture', models.CharField(choices=[('LUXE', 'Luxe'), ('NORMALE', 'Normale')], default='NORMALE', max_length=10)),
                ('stock', models.IntegerField(default=5)),
                ('prix_de_reservation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_voiture', models.CharField(choices=[('Gamme_Familiale', 'Gamme Familiale'), ('Gamme_SUV', 'Gamme SUV'), ('Gamme_Citadines', 'Gamme Citadines'), ('prestige', 'prestige'), ('SUVs', 'SUVs'), ('Berlines_Limousines', 'Berlines Limousines')], default='Gamme_Familiale', max_length=20)),
                ('position', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_depart', models.CharField(max_length=100)),
                ('lieu_arrivee', models.CharField(max_length=100)),
                ('datelocation', models.CharField(max_length=100)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_App.voiture')),
            ],
        ),
    ]
